### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by User-790** [luke20332/LLPL#1]
Hello, love the work I’ve had this unfamiliar car parked on my street for a couple days and I was wondering by running their plate using your program am I able to find specifications as to who the person is, contact information etc?

**Comment by luke20332** [comment]
Hi, apologies for the late reply, I hadn't noticed this until recently.

Unfortunately, my project searches up the detected license plate on rate-driver.co.uk, so any information that can be found will be on that site. As it is all user submitted, it is more about what the general public thinks of that driver rather than specific information such as contact details.

**Comment by User-790** [comment]
Great thank you!
